#: See https://github.com/pages-themes/cayman#usage
theme: jekyll-theme-cayman
title: "Stephen Krewson"
description: "19C Literature, Computer Vision, Arts et Métiers"

github: metadata
markdown: kramdown

# support emoji
gems:
  - jemoji

# https://jekyllrb.com/docs/collections/ (TODO: poems, music?)
collections:

  articles:
    layout: article
    output: true